package br.com.agenda.model;
// Generated 02/12/2017 17:00:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Caderno generated by hbm2java
 */
public class Caderno  implements java.io.Serializable {


     private Integer idCaderno;
     private String nome;
     private Set contatos = new HashSet(0);

    public Caderno() {
    }

	
    public Caderno(String nome) {
        this.nome = nome;
    }
    public Caderno(String nome, Set contatos) {
       this.nome = nome;
       this.contatos = contatos;
    }
   
    public Integer getIdCaderno() {
        return this.idCaderno;
    }
    
    public void setIdCaderno(Integer idCaderno) {
        this.idCaderno = idCaderno;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getContatos() {
        return this.contatos;
    }
    
    public void setContatos(Set contatos) {
        this.contatos = contatos;
    }
}


