package br.com.agenda.model;
// Generated 02/12/2017 17:00:55 by Hibernate Tools 4.3.1


import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Contato generated by hbm2java
 */
public class Contato  implements java.io.Serializable {

    private SimpleDateFormat sdf1= new SimpleDateFormat("dd/MM/yyyy");
     private Integer idContato;
     private Caderno caderno;
     private String nome;
     private String telefoneFixo;
     private String telefoneCelular;
     private String endereco;
     private String cidade;
     private Date dataNacimento;
     private String email;
     private String observacao;

    public Contato() {
    }

	
    public Contato(Caderno caderno, String nome) {
        this.caderno = caderno;
        this.nome = nome;
    }
    public Contato(Caderno caderno, String nome, String telefoneFixo, String telefoneCelular, String endereco, String cidade, Date dataNacimento, String email, String observacao) {
       this.caderno = caderno;
       this.nome = nome;
       this.telefoneFixo = telefoneFixo;
       this.telefoneCelular = telefoneCelular;
       this.endereco = endereco;
       this.cidade = cidade;
       this.dataNacimento = dataNacimento;
       this.email = email;
       this.observacao = observacao;
    }
   
    public Integer getIdContato() {
        return this.idContato;
    }
    
    public void setIdContato(Integer idContato) {
        this.idContato = idContato;
    }
    public Caderno getCaderno() {
        return this.caderno;
    }
    
    public void setCaderno(Caderno caderno) {
        this.caderno = caderno;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTelefoneFixo() {
        return this.telefoneFixo;
    }
    
    public void setTelefoneFixo(String telefoneFixo) {
        this.telefoneFixo = telefoneFixo;
    }
    public String getTelefoneCelular() {
        return this.telefoneCelular;
    }
    
    public void setTelefoneCelular(String telefoneCelular) {
        this.telefoneCelular = telefoneCelular;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public Date getDataNacimento() {
        return this.dataNacimento;
    }
    
    public void setDataNacimento(Date dataNacimento) {
        this.dataNacimento = dataNacimento;
    }
    
    public void setDataNacimento(String date){
        try{
        sdf1.setLenient (false); 
        if(!date.equals(""))
            this.dataNacimento = sdf1.parse (date);
        else
            this.dataNacimento = null;
        }catch(Exception ex){
             ex.printStackTrace();            
        }
    }
    
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }


    public String getStringDataNac() {
        if(dataNacimento != null)
            return sdf1.format(dataNacimento);
        return null;
    }

}


