/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.agenda.view;

import br.com.agenda.model.Contato;
import br.com.agenda.control.ControleAbasContato;
import br.com.agenda.control.ControleTabelaCaderno;
import br.com.agenda.control.ControleTabelaContato;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio
 */
public class InicialView extends javax.swing.JFrame {
    
private final ControleTabelaCaderno cTabelaCaderno;
private final ControleAbasContato cAbaContato;
private final ControleTabelaContato cTabelaContato;

    /**
     * Creates new form InicialView
     */
    public InicialView() {
        initComponents();
        this.cTabelaContato = new ControleTabelaContato(ModeloTContato,jTableResultadoPesquisa);
        this.cAbaContato = new ControleAbasContato(jPanelPesquisarContato,jPanelNovoContato);
        this.cTabelaCaderno = new ControleTabelaCaderno(ModeloTCaderno,jTableAgendas,cAbaContato);
        //cTabelaCaderno.iniTCaderno();
        configSelecaoT(0);
    }
   


//-------marca posição na tabela caderno e habilita as abas ------
    private void configSelecaoT(int p){
        cTabelaCaderno.iniTCaderno();
        if(jTableAgendas.getRowCount()>0){
            jTableAgendas.setRowSelectionInterval(0, p);
            cAbaContato.bloquearLiberarCampos(true);
            jLabelCaderno.setText(cTabelaCaderno.getAgendas().get(p).getNome());
            cTabelaContato.carregarTContato(cTabelaCaderno.getAgendas().get(p));
        }
    }
    
    
    private void salvarContato(){
        if(!jTextFieldNome.getText().equals("")){
            if(jToggleButtonEditarContato.isSelected()){
                int row = jTableResultadoPesquisa.getSelectedRow();
                Contato c = cTabelaContato.getContatos().get(row);
                getCampos(c);
                cTabelaContato.atualizarContatos(c);
            } else{
                Contato c = new Contato();
                getCampos(c);
                cTabelaContato.inserirContatos(c); 
            }
        }else
            JOptionPane.showMessageDialog(null, "Contato sem nome");
        jToggleButtonEditarContato.setSelected(false);
    }

    private void limparCampos(){
        jTextFieldNome.setText("");
        jFormattedTextFieldCel.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldTel.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEnd.setText("");
        jFormattedTextFieldDataNaci.setText("");
        jTextAreaObservacao.setText("");
        jToggleButtonEditarContato.setSelected(false);
        jToggleButtonExcluirContato.setSelected(false);
    }
    
    private void getCampos(Contato c){
        c.setNome(jTextFieldNome.getText());
        c.setTelefoneCelular(jFormattedTextFieldCel.getText());
        c.setCidade(jTextFieldCidade.getText());
        c.setTelefoneFixo(jFormattedTextFieldTel.getText());
        c.setEmail(jTextFieldEmail.getText());
        c.setEndereco(jTextFieldEnd.getText());
        c.setDataNacimento(jFormattedTextFieldDataNaci.getText());
        c.setObservacao(jTextAreaObservacao.getText()); 
        limparCampos();      
    }
    
    private void setCampos(int row){
        
        Contato c = cTabelaContato.getContatos().get(row);
        jTextFieldNome.setText(c.getNome());
        jFormattedTextFieldCel.setText(c.getTelefoneCelular());
        jTextFieldCidade.setText(c.getCidade());
        jFormattedTextFieldTel.setText(c.getTelefoneFixo());
        jTextFieldEmail.setText(c.getEmail());
        jTextFieldEnd.setText(c.getEndereco());
        jFormattedTextFieldDataNaci.setText(c.getStringDataNac());
        jTextAreaObservacao.setText(c.getObservacao());  
    }
    
    
    private void telaEscolherCaderno(){
        if(jTableAgendas.getSelectedRow() == -1){
        EscolherAgendaView selecionarAgenda = new EscolherAgendaView(cTabelaCaderno.getAgendas());
        selecionarAgenda.setVisible(true);
        int p = selecionarAgenda.getPosicao();
        if(p !=-1)
            configSelecaoT(p);
        selecionarAgenda.dispose(); 
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAgendas = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonNovaAgenda = new javax.swing.JButton();
        jButtonEditarAgenda = new javax.swing.JButton();
        jButtonExcluirAgenda = new javax.swing.JButton();
        jButtonNovoContato = new javax.swing.JButton();
        jToggleButtonEditarContato = new javax.swing.JToggleButton();
        jToggleButtonExcluirContato = new javax.swing.JToggleButton();
        jButtonSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPesquisarContato = new javax.swing.JPanel();
        jLabelPesCont = new javax.swing.JLabel();
        jLabelCamDPes = new javax.swing.JLabel();
        jTextFieldPalavraChave = new javax.swing.JTextField();
        jLabelPalaCha = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jComboBoxCampoPesquisa = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableResultadoPesquisa = new javax.swing.JTable();
        jButtonPesquisa = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaObservacao1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabelCade = new javax.swing.JLabel();
        jLabelCaderno = new javax.swing.JLabel();
        jPanelNovoContato = new javax.swing.JPanel();
        jLabelNovoCont = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelNome = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelCel = new javax.swing.JLabel();
        jLabelEnd = new javax.swing.JLabel();
        jLabelDN = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelObservacao = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldEnd = new javax.swing.JTextField();
        jFormattedTextFieldDataNaci = new javax.swing.JFormattedTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaObservacao = new javax.swing.JTextArea();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelCaderno1 = new javax.swing.JLabel();
        jLabelCade1 = new javax.swing.JLabel();
        jFormattedTextFieldTel = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemCriarAgenda = new javax.swing.JMenuItem();
        jMenuItemExcluirAgenda = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemEditarContato = new javax.swing.JMenuItem();
        jMenuItemCriarContato = new javax.swing.JMenuItem();
        jMenuItemApagarContato = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agenda");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(900, 790));
        getContentPane().setLayout(null);

        jTableAgendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Agenda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ModeloTCaderno = (DefaultTableModel)jTableAgendas.getModel();
        jTableAgendas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableAgendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAgendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAgendas);
        if (jTableAgendas.getColumnModel().getColumnCount() > 0) {
            jTableAgendas.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 76, 127, 666);

        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setInheritsPopupMenu(true);

        jButtonNovaAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_add_agenda.png"))); // NOI18N
        jButtonNovaAgenda.setText("Nova Agenda");
        jButtonNovaAgenda.setFocusable(false);
        jButtonNovaAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovaAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNovaAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaAgendaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonNovaAgenda);

        jButtonEditarAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_editar_agenda.png"))); // NOI18N
        jButtonEditarAgenda.setText("Editar Agenda");
        jButtonEditarAgenda.setFocusable(false);
        jButtonEditarAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonEditarAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonEditarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAgendaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonEditarAgenda);

        jButtonExcluirAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_excluir_agenda.png"))); // NOI18N
        jButtonExcluirAgenda.setText("Excuir Agenda");
        jButtonExcluirAgenda.setFocusable(false);
        jButtonExcluirAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExcluirAgenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonExcluirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirAgendaActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonExcluirAgenda);

        jButtonNovoContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_novo_contato.png"))); // NOI18N
        jButtonNovoContato.setText("Novo Contato");
        jButtonNovoContato.setFocusable(false);
        jButtonNovoContato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNovoContato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonNovoContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoContatoActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonNovoContato);

        jToggleButtonEditarContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_editar_contato.png"))); // NOI18N
        jToggleButtonEditarContato.setText("Editar Contato");
        jToggleButtonEditarContato.setFocusable(false);
        jToggleButtonEditarContato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonEditarContato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonEditarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEditarContatoActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonEditarContato);

        jToggleButtonExcluirContato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_excluir_contato.png"))); // NOI18N
        jToggleButtonExcluirContato.setText("Excluir Contato");
        jToggleButtonExcluirContato.setFocusable(false);
        jToggleButtonExcluirContato.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButtonExcluirContato.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButtonExcluirContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonExcluirContatoActionPerformed(evt);
            }
        });
        jToolBar1.add(jToggleButtonExcluirContato);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_sai.png"))); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.setFocusable(false);
        jButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonSair);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 756, 70);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setEnabled(jPanel1.isEnabled());

        jLabelPesCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPesCont.setText("Pesquisar Contato");

        jLabelCamDPes.setText("Campo de pesquisa:");

        jLabelPalaCha.setText("Palavra chave:");

        jComboBoxCampoPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Telefone Fixo", "Telefone Celular", "Endereco", "Email", "Observacao" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTableResultadoPesquisa, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jScrollPane3, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jTableResultadoPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tel. Fixo", "Tel. Cel.", "Endereço", "Data de Nacimento", "Cidade", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ModeloTContato = (DefaultTableModel)jTableResultadoPesquisa.getModel();
        jTableResultadoPesquisa.setColumnSelectionAllowed(true);
        jTableResultadoPesquisa.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableResultadoPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableResultadoPesquisaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableResultadoPesquisa);
        jTableResultadoPesquisa.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableResultadoPesquisa.getColumnModel().getColumnCount() > 0) {
            jTableResultadoPesquisa.getColumnModel().getColumn(0).setMinWidth(10);
            jTableResultadoPesquisa.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableResultadoPesquisa.getColumnModel().getColumn(1).setPreferredWidth(12);
            jTableResultadoPesquisa.getColumnModel().getColumn(2).setPreferredWidth(12);
            jTableResultadoPesquisa.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTableResultadoPesquisa.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTableResultadoPesquisa.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTableResultadoPesquisa.getColumnModel().getColumn(6).setPreferredWidth(90);
        }

        jButtonPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_pesquisar_contato.png"))); // NOI18N
        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextAreaObservacao1, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jScrollPane4, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jTextAreaObservacao1.setColumns(20);
        jTextAreaObservacao1.setRows(5);
        jTextAreaObservacao1.setFocusable(false);
        jScrollPane4.setViewportView(jTextAreaObservacao1);

        jLabel1.setText("Observação");

        jLabelCade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCade.setText("Agenda");

        jLabelCaderno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jLabelCaderno1, org.jdesktop.beansbinding.ELProperty.create("${text}"), jLabelCaderno, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout jPanelPesquisarContatoLayout = new javax.swing.GroupLayout(jPanelPesquisarContato);
        jPanelPesquisarContato.setLayout(jPanelPesquisarContatoLayout);
        jPanelPesquisarContatoLayout.setHorizontalGroup(
            jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarContatoLayout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisarContatoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabelPesCont, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCade)
                .addGap(18, 18, 18)
                .addComponent(jLabelCaderno, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(jPanelPesquisarContatoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisarContatoLayout.createSequentialGroup()
                        .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3))
                        .addContainerGap())
                    .addGroup(jPanelPesquisarContatoLayout.createSequentialGroup()
                        .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButtonPesquisa)
                            .addGroup(jPanelPesquisarContatoLayout.createSequentialGroup()
                                .addComponent(jLabelCamDPes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelPalaCha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 77, Short.MAX_VALUE))))
        );
        jPanelPesquisarContatoLayout.setVerticalGroup(
            jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarContatoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCade)
                    .addComponent(jLabelCaderno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCamDPes)
                        .addComponent(jComboBoxCampoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPesquisarContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelPalaCha)
                        .addComponent(jTextFieldPalavraChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jButtonPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jTabbedPane1.addTab("Pesquisar Contato", jPanelPesquisarContato);

        jLabelNovoCont.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNovoCont.setText("Novo Contato");

        jLabelNome.setText("Nome:");

        jLabelTel.setText("Tel:");

        jLabelCel.setText("Cel:");

        jLabelEnd.setText("Endereço:");

        jLabelDN.setText("Data Naci.:");

        jLabelEmail.setText("Email:");

        jLabelObservacao.setText("Observação:");

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jTextFieldEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEndActionPerformed(evt);
            }
        });

        jFormattedTextFieldDataNaci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelCidade.setText("Cidade:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextAreaObservacao, org.jdesktop.beansbinding.ELProperty.create("${editable}"), jScrollPane2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jTextAreaObservacao.setColumns(20);
        jTextAreaObservacao.setRows(5);
        jTextAreaObservacao.setEnabled(jPanel1.isEnabled());
        jScrollPane2.setViewportView(jTextAreaObservacao);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/agenda/assets/ico_cancelar.png"))); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelCaderno1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCaderno1.setText(" ");

        jLabelCade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCade1.setText("Agenda");

        try {
            jFormattedTextFieldTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextFieldCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#:####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanelNovoContatoLayout = new javax.swing.GroupLayout(jPanelNovoContato);
        jPanelNovoContato.setLayout(jPanelNovoContatoLayout);
        jPanelNovoContatoLayout.setHorizontalGroup(
            jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                        .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelObservacao)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelTel)
                            .addComponent(jLabelDN))
                        .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCancelar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome)
                                    .addComponent(jScrollPane2)
                                    .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                                        .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                    .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jFormattedTextFieldDataNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabelEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldEmail)))
                                .addGap(112, 112, 112))))
                    .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                        .addComponent(jLabelNovoCont)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCade1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCaderno1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                        .addComponent(jLabelEnd)
                        .addGap(186, 186, 186))
                    .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                        .addComponent(jLabelCidade)
                        .addGap(25, 25, 25)
                        .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnd)
                            .addComponent(jTextFieldCidade))
                        .addGap(112, 112, 112))))
        );
        jPanelNovoContatoLayout.setVerticalGroup(
            jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNovoContatoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNovoCont, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCade1)
                    .addComponent(jLabelCaderno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTel)
                    .addComponent(jLabelCel)
                    .addComponent(jFormattedTextFieldTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDN)
                    .addComponent(jFormattedTextFieldDataNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail))
                .addGap(11, 11, 11)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnd)
                    .addComponent(jTextFieldEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCidade)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelObservacao)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelNovoContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Novo Contato", jPanelNovoContato);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(133, 76, 712, 637);

        jMenuArquivo.setText("Arquivo");

        jMenuItemCriarAgenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCriarAgenda.setText("Criar Agenda");
        jMenuItemCriarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarAgendaActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemCriarAgenda);

        jMenuItemExcluirAgenda.setText("Excluir Agenda");
        jMenuItemExcluirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirAgendaActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemExcluirAgenda);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuEditar.setText("Editar");

        jMenuItemEditarContato.setText("Editar Contato");
        jMenuItemEditarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditarContatoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemEditarContato);

        jMenuItemCriarContato.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCriarContato.setText("Criar Contato");
        jMenuItemCriarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCriarContatoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemCriarContato);

        jMenuItemApagarContato.setText("Apagar Contato");
        jMenuItemApagarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemApagarContatoActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemApagarContato);

        jMenuBar1.add(jMenuEditar);

        setJMenuBar(jMenuBar1);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonNovaAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaAgendaActionPerformed
        cTabelaCaderno.inserirCadernos();
        configSelecaoT(0);
    }//GEN-LAST:event_jButtonNovaAgendaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonExcluirAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirAgendaActionPerformed
     cTabelaCaderno.excluirCadernos();
     configSelecaoT(0);
    }//GEN-LAST:event_jButtonExcluirAgendaActionPerformed
   
    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        String itemSele = (String)jComboBoxCampoPesquisa.getSelectedItem();
        String chave = (String)jTextFieldPalavraChave.getText();
        if(chave.equals(""))
            cTabelaContato.atualizarTcontato();
        else{
            cTabelaContato.carregarContatosFiltro(itemSele.replaceAll(" ",""), chave);
        }
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonEditarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAgendaActionPerformed
        cTabelaCaderno.atualizarCaderno();
        configSelecaoT(0);
    }//GEN-LAST:event_jButtonEditarAgendaActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTableAgendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAgendasMouseClicked
        configSelecaoT(jTableAgendas.getSelectedRow());
    }//GEN-LAST:event_jTableAgendasMouseClicked

    private void jButtonNovoContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoContatoActionPerformed
        if(jTableAgendas.getRowCount() ==0)
            JOptionPane.showMessageDialog(null, "Crie uma agenda primeiro");
        else {
            telaEscolherCaderno();
            jTabbedPane1.setSelectedIndex(1);       //aba de criar contato/editar
        }
    }//GEN-LAST:event_jButtonNovoContatoActionPerformed

    private void jTableResultadoPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableResultadoPesquisaMouseClicked
        int row = jTableResultadoPesquisa.getSelectedRow();
        if(row !=-1){
//------controle da caixa de texto obsevação----
            List<Contato> c = cTabelaContato.getContatos();
            jTextAreaObservacao1.setText(c.get(row).getObservacao());

    //------controle de excluir contatos------
            if(jToggleButtonExcluirContato.isSelected()){
                cTabelaContato.excluirContatos(row);
                jToggleButtonExcluirContato.setSelected(false);
                jTextAreaObservacao1.setText("");
//------controle de editar contatos------            
            }else if(jToggleButtonEditarContato.isSelected()){
                jTabbedPane1.setSelectedIndex(1);       //aba de criar contato/editar
                setCampos(row);
            }
        }else
            jTextAreaObservacao1.setText("");        
    }//GEN-LAST:event_jTableResultadoPesquisaMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
       salvarContato();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jToggleButtonExcluirContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonExcluirContatoActionPerformed
        if(jTableAgendas.getRowCount() ==0){
            JOptionPane.showMessageDialog(null, "Crie uma agenda primeiro");
            jToggleButtonExcluirContato.setSelected(false);
        }else {
            if(jToggleButtonExcluirContato.isSelected()){
                if(jToggleButtonEditarContato.isSelected())
                    jToggleButtonEditarContato.setSelected(false);
                telaEscolherCaderno();

                JOptionPane.showMessageDialog(null, "Selecione o contato para excluir");
                cTabelaContato.iniTContato();
                jTabbedPane1.setSelectedIndex(0);       //aba de pesquisa
            }
        }    
    }//GEN-LAST:event_jToggleButtonExcluirContatoActionPerformed

    private void jToggleButtonEditarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEditarContatoActionPerformed
        if(jTableAgendas.getRowCount() ==0){
            JOptionPane.showMessageDialog(null, "Crie uma agenda primeiro");
            jToggleButtonEditarContato.setSelected(false);
        }else {
            if(jToggleButtonEditarContato.isSelected()){    
                if(jToggleButtonExcluirContato.isSelected())
                    jToggleButtonExcluirContato.setSelected(false);
                telaEscolherCaderno(); 

                JOptionPane.showMessageDialog(null, "Selecione o contato para editar");
                cTabelaContato.iniTContato();
                jTabbedPane1.setSelectedIndex(0);       //aba de pesquisa
            }
        }        
    }//GEN-LAST:event_jToggleButtonEditarContatoActionPerformed

    private void jMenuItemCriarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarAgendaActionPerformed
        cTabelaCaderno.inserirCadernos();
        configSelecaoT(0);
    }//GEN-LAST:event_jMenuItemCriarAgendaActionPerformed

    private void jMenuItemExcluirAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirAgendaActionPerformed
        cTabelaCaderno.excluirCadernos();
        configSelecaoT(0);     
    }//GEN-LAST:event_jMenuItemExcluirAgendaActionPerformed

    private void jMenuItemCriarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCriarContatoActionPerformed
        if(jTableAgendas.getRowCount() ==0)
            JOptionPane.showMessageDialog(null, "Crie uma agenda primeiro");
        else {
            telaEscolherCaderno();
            jTabbedPane1.setSelectedIndex(1);       //aba de criar contato/editar
        }       
    }//GEN-LAST:event_jMenuItemCriarContatoActionPerformed

    private void jMenuItemEditarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditarContatoActionPerformed
        if(jTableAgendas.getRowCount() ==0){
            JOptionPane.showMessageDialog(null, "Crie uma agenda primeiro");
            jToggleButtonEditarContato.setSelected(false);
        }else {
            if(!jToggleButtonEditarContato.isSelected()){
                jToggleButtonEditarContato.setSelected(true);
                if(jToggleButtonExcluirContato.isSelected())
                    jToggleButtonExcluirContato.setSelected(false);
                telaEscolherCaderno(); 

                JOptionPane.showMessageDialog(null, "Selecione o contato para editar");
                cTabelaContato.iniTContato();
                jTabbedPane1.setSelectedIndex(0);       //aba de pesquisa
            }
        }         
    }//GEN-LAST:event_jMenuItemEditarContatoActionPerformed

    private void jMenuItemApagarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemApagarContatoActionPerformed
        if(jTableAgendas.getRowCount() ==0){
            JOptionPane.showMessageDialog(null, "Crie uma agenda primeiro");
            jToggleButtonExcluirContato.setSelected(false);
        }else {
            if(!jToggleButtonExcluirContato.isSelected()){
                jToggleButtonExcluirContato.setSelected(true);
                if(jToggleButtonEditarContato.isSelected())
                    jToggleButtonEditarContato.setSelected(false);
                telaEscolherCaderno();

                JOptionPane.showMessageDialog(null, "Selecione o contato para excluir");
                cTabelaContato.iniTContato();
                jTabbedPane1.setSelectedIndex(0);       //aba de pesquisa
            }
        } 
    }//GEN-LAST:event_jMenuItemApagarContatoActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEndActionPerformed
    }//GEN-LAST:event_jTextFieldEndActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditarAgenda;
    private javax.swing.JButton jButtonExcluirAgenda;
    private javax.swing.JButton jButtonNovaAgenda;
    private javax.swing.JButton jButtonNovoContato;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCampoPesquisa;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataNaci;
    private javax.swing.JFormattedTextField jFormattedTextFieldTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCade;
    private javax.swing.JLabel jLabelCade1;
    private javax.swing.JLabel jLabelCaderno;
    private javax.swing.JLabel jLabelCaderno1;
    private javax.swing.JLabel jLabelCamDPes;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelDN;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEnd;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovoCont;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelPalaCha;
    private javax.swing.JLabel jLabelPesCont;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemApagarContato;
    private javax.swing.JMenuItem jMenuItemCriarAgenda;
    private javax.swing.JMenuItem jMenuItemCriarContato;
    private javax.swing.JMenuItem jMenuItemEditarContato;
    private javax.swing.JMenuItem jMenuItemExcluirAgenda;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelNovoContato;
    private javax.swing.JPanel jPanelPesquisarContato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAgendas;
    private javax.swing.JTable jTableResultadoPesquisa;
    private javax.swing.JTextArea jTextAreaObservacao;
    private javax.swing.JTextArea jTextAreaObservacao1;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEnd;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPalavraChave;
    private javax.swing.JToggleButton jToggleButtonEditarContato;
    private javax.swing.JToggleButton jToggleButtonExcluirContato;
    private javax.swing.JToolBar jToolBar1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel ModeloTCaderno;
    private DefaultTableModel ModeloTContato;
}
